// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMs0U2uo2NJAULTr0GHoeDx9MO5tFs4D4',
    appId: '1:1046859848300:web:0ab7819089488587d71649',
    messagingSenderId: '1046859848300',
    projectId: 'todo-app-9d80f',
    authDomain: 'todo-app-9d80f.firebaseapp.com',
    storageBucket: 'todo-app-9d80f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbkRDZs090dymX_jx71WuLBCNu2DGRHM',
    appId: '1:1046859848300:android:36f96cc288e5391bd71649',
    messagingSenderId: '1046859848300',
    projectId: 'todo-app-9d80f',
    storageBucket: 'todo-app-9d80f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfo4SlAHbk5J0lDeyD1-pxZ41sY2UJRKU',
    appId: '1:1046859848300:ios:70c4a31f82b55195d71649',
    messagingSenderId: '1046859848300',
    projectId: 'todo-app-9d80f',
    storageBucket: 'todo-app-9d80f.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfo4SlAHbk5J0lDeyD1-pxZ41sY2UJRKU',
    appId: '1:1046859848300:ios:70c4a31f82b55195d71649',
    messagingSenderId: '1046859848300',
    projectId: 'todo-app-9d80f',
    storageBucket: 'todo-app-9d80f.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMs0U2uo2NJAULTr0GHoeDx9MO5tFs4D4',
    appId: '1:1046859848300:web:1f7e0e98bffeefdbd71649',
    messagingSenderId: '1046859848300',
    projectId: 'todo-app-9d80f',
    authDomain: 'todo-app-9d80f.firebaseapp.com',
    storageBucket: 'todo-app-9d80f.firebasestorage.app',
  );
}
